development:
  adapter: postgresql
  encoding: unicode
  database: fileshare_development
  pool: 5
  username: postgres
  password: letmein00

test:
  adapter: postgresql
  encoding: unicode
  database: fileshare_test
  pool: 5
  username: postgres
  password: letmein00

production:
  adapter: postgresql
  encoding: unicode
  database: fileshare_production
  pool: 5
  username: postgres
  password: letmein00

