development:
  adapter: postgresql
  encoding: unicode
  database: fileshare_development
  pool: 5
  username: <username>
  password: <password>

test:
  adapter: postgresql
  encoding: unicode
  database: fileshare_test
  pool: 5
  username: <username>
  password: <password>

production:
  adapter: postgresql
  encoding: unicode
  database: fileshare_production
  pool: 5
  username: <username>
  password: <password>

