development:
  access_key_id: AKIAIFIBH62P2Q55PUNA
  secret_access_key: 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
  bucket: my_fileshare
production:
  access_key_id: AKIAIFIBH62P2Q55PUNA
  secret_access_key: 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
  bucket: my_fileshare
