development:
  access_key_id: <YOUR_ACCESS_KEY_ID_HERE>
  secret_access_key: <YOUR_SECRET_ACCESS_KEY_ID_HERE>
  bucket: <YOUR_BUCKET_NAME_HERE>
production:
  access_key_id: <YOUR_ACCESS_KEY_ID_HERE>
  secret_access_key: <YOUR_SECRET_ACCESS_KEY_ID_HERE>
  bucket: <YOUR_BUCKET_NAME_HERE>
